### ISSUE TITLE
Git merge

### ISSUE THREAD

**Issue by RenatoCaixeta** [avitaliano/iesb-posbi-dataquality#1]
https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

Foreword: Your fork is the "origin" and the repository you forked from is the "upstream".

Let's assume that you cloned already your fork to your computer with a command like this:

git clone git@github.com:your_name/project_name.git
cd project_name
If that is given then you need to continue in this order:

Add the "upstream" to your cloned repository ("origin"):
git remote add upstream git@github.com:original_author/project_name.git
Fetch the commits (and branches) from the "upstream":
git fetch upstream
Switch to the "master" branch of your fork ("origin"):
git checkout master
Stash the changes of your "master" branch:
git stash
Merge the changes from the "master" branch of the "upstream" into your the "master" branch of your "origin":
git merge upstream/master
Resolve merge conflicts if any and commit your merge
git commit -am "Merged from upstream"
Push the changes to your fork
git push
Get back your stashed changes (if any)
git stash pop
You're done! Congratulations!
GitHub also provides instructions for this topic: Syncing a fork

**Comment by avitaliano** [comment]
Creio que o que fizemos errado foi a sintaxe da linha "git merge upstream/master".
Usamos "git merge upstream master", ou talvez o git stash seja necessário.
Podemos testar na próxima aula.
Obrigado, Renato.
